# Generated by Django 4.2.15 on 2024-08-28 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='bedroom',
            new_name='bedrooms',
        ),
        migrations.RenameField(
            model_name='property',
            old_name='creates_at',
            new_name='created_at',
        ),
    ]
