# Generated by Django 4.2.15 on 2024-09-02 15:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('property', '0003_reservation'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='favourited',
            field=models.ManyToManyField(blank=True, related_name='favourites', to=settings.AUTH_USER_MODEL),
        ),
    ]
