# Generated by Django 4.2.15 on 2024-09-02 16:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('property', '0004_property_favourited'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='favourited',
        ),
        migrations.AddField(
            model_name='property',
            name='favorited',
            field=models.ManyToManyField(blank=True, related_name='favorites', to=settings.AUTH_USER_MODEL),
        ),
    ]
